config/routes.rb
Rails.application.routes.draw do
  root 'homes#latest'
  devise_for :users
  resources :articles do
    resources :comments, only: [:create]
    resource :votes, only: [:update, :destroy]
  end
  resources :my_articles, only: [:index]

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments
  has_many :votes

  validates :title, presence: true, length: { minimum: 10 }
  validates :content, presence: true, length: { minimum: 50 }

  def votes_count(value)
    votes.where(value: value).count
  end

  def increase_views_count
    Article.increment_counter(:views_count, self.id)
  end

  def self.hot_articles
    # SELECT articles.*, IFNULL(SUM(votes.value), 0)
    # FROM articles
    # LEFT JOIN votes
    #   ON votes.article_id = articles.id
    # GROUP BY articles.id
    # ORDER BY SUM(votes.value) DESC
    # LIMIT 5;
    joins('LEFT JOIN votes ON votes.article_id = articles.id')
      .group('articles.id')
      .order('SUM(votes.value) DESC')
      .limit(5)
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :content, presence: true
end

app/models/user.rb
require 'carrierwave/orm/activerecord'

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true

  def vote!(article, value)
    vote = Vote.where(user: self, article: article).first_or_initialize
    vote.value = value
    vote.save!
  end

  def unvote!(article)
    Vote.where(user: self, article: article).delete_all
  end

  def voted?(article, value)
    Vote.where(user: self, article: article, value: value).exists?
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :article_id, uniqueness: { scope: :user_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def check_user_signed_in
    if current_user == nil
      redirect_to new_user_session_path, alert: 'Phải đăng nhập trước'
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update).concat([:avatar, :name])
    devise_parameter_sanitizer.for(:sign_up).concat([:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_user_signed_in, except: [:show]

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to @article, notice: 'Đăng bài thành công'
    else
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
    @article.increase_views_count
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article, notice: 'Sửa bài thành công'
    else
      render :edit
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy

    redirect_to my_articles_path
  end

  def article_params
    params.require(:article).permit(:title, :content, :category_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_user_signed_in

  def create
    @article = Article.find(params[:article_id])
    @comment = Comment.new(params.require(:comment).permit(:content))
    @comment.user = current_user
    @comment.article = @article

    if @comment.save
      redirect_to article_path(@article)
    else
      redirect_to article_path(@article), alert: 'Bình luận không hợp lệ'
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def latest
    @articles = Article.order('created_at DESC').limit(5)
  end

  def hot
  end
end

app/controllers/my_articles_controller.rb
class MyArticlesController < ApplicationController
  before_action :check_user_signed_in

  def index
    @articles = current_user.articles
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :check_user_signed_in

  def update
    article = Article.find(params[:article_id])
    value = params.require(:vote).require(:value)

    current_user.vote!(article, value)

    redirect_to article
  end

  def destroy
    article = Article.find(params[:article_id])
    current_user.unvote!(article)

    redirect_to article
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  AVATAR_VERSIONS = {
    tiny: {
      :format => "png",
      :width => 20,
      :height => 20,
      :crop => :thumb,
    },
    thumb: {
      :format => "png",
      :width => 64,
      :height => 64,
      :crop => :thumb,
    }
  }

  def render_avatar(user, version)
    class_name = ['avatar', 'avatar-' + version.to_s]

    if user.avatar.full_public_id
      cl_image_tag(user.avatar.full_public_id, AVATAR_VERSIONS[version].merge(class: class_name))
    else
      image_tag 'no_avatar.svg', AVATAR_VERSIONS[version].slice(:width, :height).merge(class: class_name)
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/articles/_comment_form.html.erb
<div class="comment-form">
  <div class="media">
    <div class="media-left">
      <%= render_avatar(current_user, :thumb) %>
    </div>
    <div class="media-body">
      <%= form_for [article, Comment.new] do |f| %>
        <div class="form-group">
          <%= f.text_area :content, placeholder: 'Bình luận của bạn', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit 'Lưu', class: 'btn btn-default pull-right' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/_comments_section.html.erb
<div class="article-comments">
  <% if user_signed_in? %>
    <%= render 'articles/comment_form', article: article %>
  <% else %>
    <%= link_to "Hãy đăng nhập để bình luận", new_user_session_path %>
  <% end %>

  <hr />

  <div class="comments">
    <% article.comments.order(created_at: :desc).each do |comment| %>
      <div class="comment media">
        <div class="media-left">
          <%= render_avatar(comment.user, :thumb) %>
        </div>
        <div class="media-body">
          <div>
            <span class="commentor-name"><%= comment.user.name %></span>
            &middot;
            <span class="comment-time">cách đây <%= time_ago_in_words(comment.created_at) %></span>
          </div>
          <div class"comment-content">
            <%= simple_format comment.content %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_footer.html.erb
<div class="article-footer">
  <div class="row">
    <div class="media col-xs-8">
      <div class="media-left">
        <%= render_avatar(article.user, :thumb) %>
      </div>
      <div class="media-body">
        <div>
          <span class="author-name"><%= article.user.name %></span>
          &middot;
          <span class="article-time">cách đây <%= time_ago_in_words(article.created_at) %></span>
        </div>
        <div class="article-stats"><span class="stats-label">Xem:</span> <%= article.views_count%> lượt</div>
        <div class="article-stats"><span class="stats-label">Bình luận:</span> <%= article.comments.count %> lượt</div>
        <div class="article-stats"><span class="stats-label">Danh mục:</span> <%= article.category.name %></div>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="pull-right">
        <%= render 'articles/vote_buttons', article: article %>
      </div>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div class="error-messages text-danger bg-danger">
      <h3>Có <%= @article.errors.count %> lỗi xảy ra, vui lòng kiểm tra lại dữ liệu nhập:</h3>
      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, 'Tiêu đề' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :category, 'Danh mục' %>
    <%= f.select :category_id, Category.all.map{ |c| [c.name, c.id] }, {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content, 'Nội dung' %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Đăng bài', class: 'btn btn-default center-block' %>
  </div>
<% end %>

app/views/articles/_vote_button.html.erb
<% if current_user.voted?(article, value) %>
  <%= link_to article_votes_path(article), method: :delete, class:"btn active btn-default btn-lg" do %>
    <span class="glyphicon glyphicon-thumbs-<%= value == 1 ? 'up' : 'down' %>"></span>
    <%= article.votes_count(value) %>
  <% end %>
<% else %>
  <%= link_to article_votes_path(article, vote: {value: value}), method: :put, class:"btn btn-default btn-lg" do %>
    <span class="glyphicon glyphicon-thumbs-<%= value == 1 ? 'up' : 'down' %>"></span>
    <%= article.votes_count(value) %>
  <% end %>
<% end %>

app/views/articles/_vote_buttons.html.erb
<div class="btn-group">
  <%= render 'articles/vote_button', article: article, value: 1 %>
  <%= render 'articles/vote_button', article: article, value: -1 %>
</div>

app/views/articles/edit.html.erb
<div class="article-form">
  <h2>Sửa bài <%= @article.title %></h2>
  <%= render 'form' %>
</div>

app/views/articles/new.html.erb
<div class="article-form">
  <h2>Đăng bài</h2>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="article-content">
  <h2><%= @article.title %></h2>

  <%= simple_format @article.content %>
</div>
<%= render 'articles/footer', article: @article %>
<%= render 'articles/comments_section', article: @article %>

app/views/homes/hot.html.erb
<h1>Homes#hot</h1>
<p>Find me in app/views/homes/hot.html.erb</p>

app/views/homes/latest.html.erb
<h2>Bài viết mới nhất</h2>

<% @articles.each do |article| %>
  <h2><%= article.title %></h2>
  <div class="article-content">
    <%= simple_format(truncate(article.content, length: 100)) %>
    <%= link_to 'Chi tiết', article_path(article) %>
  </div>
  <div class="article-footer">
    Đăng bởi <%= article.user.email %>, Cách đây <%= time_ago_in_words(article.created_at) %>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<% if alert %>
  <div class="alert alert-danger"><%= alert %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <p>&copy; 2016 Pingo, Rails basic.</p>
  </div> <!-- /container -->
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'HaiVL', root_path, class: 'navbar-brand' %>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= render_avatar(current_user, :tiny) %>
            <%= current_user.name || current_user.email %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <span class="glyphicon glyphicon-user"></span> Cập nhật thông tin cá nhân
              <% end %>
            </li>
            <li>
              <%= link_to new_article_path do %>
                <span class="glyphicon glyphicon-pencil"></span> Đăng bài
              <% end %>
            </li>
            <li>
              <%= link_to my_articles_path do %>
                <span class="glyphicon glyphicon-th-list"></span> Quản lý bài viết
              <% end %>
            </li>
            <li role="separator" class="divider"></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <span class="glyphicon glyphicon-log-out"></span> Đăng xuất
              <% end %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to 'Đăng nhập', new_user_session_path %></li>
        <li><%= link_to 'Đăng ký', new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <title>Haivl</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="main">
      <div class="container">
        <%= render 'layouts/flash_messages' %>
        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/my_articles/index.html.erb
<h2>Quản lý bài viết</h2>
<table class="table table-striped">
  <thead>
    <th>ID</th>
    <th>Tiêu đề</th>
    <td></th>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td>
          <%= link_to 'Xem', article_path(article), class: 'btn btn-default btn-sm' %>
          <%= link_to 'Sửa', edit_article_path(article), class: 'btn btn-warning btn-sm' %>
          <%= link_to 'Xoá', article_path(article), method: :delete, data: { confirm: 'Bạn có muốn xoá bài này không?' }, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>